name: HABs_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # or any version you are using
  - pandas
  - requests
  - beautifulsoup4  # installed from conda-forge
  - natsort
